name: fireboy_and_watergirl
description: "A cooperative puzzle-platformer game inspired by Fireboy and
  Watergirl, built with Flutter and Flame."
homepage: "https://github.com/DomingoMG/fireboy_watergirl_flutter"
repository: "https://github.com/DomingoMG/fireboy_watergirl_flutter"
issue_tracker: "https://github.com/DomingoMG/fireboy_watergirl_flutter/issues"
publish_to: 'none'
version: 0.0.5

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^4.2.0
  flame: ^1.25.0
  flame_audio: ^2.11.0
  flame_riverpod: ^5.4.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo/fireboy_watergirl_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/fireboy_watergirl_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/fireboy_watergirl_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/fireboy_watergirl_logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: custom_font
      fonts:
        - asset: assets/fonts/custom_font.TTF
  assets:
    - assets/audio/
    - assets/images/joystick/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/buttons/
    - assets/images/characters/
    - assets/images/doors/
    - assets/images/elevators/buttons/
    - assets/images/elevators/horizontal/
    - assets/images/elevators/vertical/
    - assets/images/gems/
    - assets/images/levers/
    - assets/images/misc/
    - assets/images/puddles/
    - assets/images/terrain/
    - assets/images/levels/
